openapi: 3.0.0
info:
  title: Russian Classical School Core API
  version: 1.0.0
  description: 'Русская классическая школа'
  contact:
    name: Anton Elshin
    email: anton.elshin@mail.ru
    url: https://vk.com/russianclassicalschool_yaroslavl
servers:
  - url: 'http://localhost:8080'
paths:
  #  Справочники

  #  Школьные классы
  /school-class:
    parameters: []
    get:
      summary: Получение списка классов по параметрам
      operationId: findSchoolClasses
      description: Получение списка классов по параметрам
      tags:
        - school-class
      parameters:
        - $ref: '#/components/parameters/search'
      responses:
        '200':
          description: OK
          headers: { }
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SchoolClassDTO'
              examples:
                example-1:
                  value:
                    - id: b06e7544-a62a-42a3-b937-73508dae48c7
                      systemName: string
                      name: string
                      description: string
    post:
      summary: Создание класса
      operationId: addSchoolClass
      description: Создание класса
      tags:
        - school-class
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchoolClassDTO'
            examples:
              example-1:
                value:
                  id: b06e7544-a62a-42a3-b937-73508dae48c7
                  systemName: string
                  name: string
                  description: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchoolClassDTO'
              examples:
                example-1:
                  value:
                    id: b06e7544-a62a-42a3-b937-73508dae48c7
                    systemName: string
                    name: string
                    description: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '422':
          description: Unprocessable Entity (WebDAV)
  '/school-class/{schoolClassId}':
    parameters:
      - $ref: '#/components/parameters/schoolClassId'
    get:
      summary: Получение класса по идентификатору
      operationId: findSchoolClassById
      description: Получение класса по идентификатору
      tags:
        - school-class
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchoolClassDTO'
              examples:
                example-1:
                  value:
                    id: b06e7544-a62a-42a3-b937-73508dae48c7
                    systemName: string
                    name: string
                    description: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '422':
          description: Unprocessable Entity (WebDAV)
    put:
      summary: Метод изменяет класс
      operationId: modifySchoolClass
      description: Метод изменяет класс
      tags:
        - school-class
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchoolClassDTO'
            examples:
              example-1:
                value:
                  id: b06e7544-a62a-42a3-b937-73508dae48c7
                  systemName: string
                  name: string
                  description: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchoolClassDTO'
              examples:
                example-1:
                  value:
                    id: b06e7544-a62a-42a3-b937-73508dae48c7
                    systemName: string
                    name: string
                    description: string
        '400':
          description: Bad Request
        '422':
          description: Unprocessable Entity (WebDAV)
    delete:
      summary: Удаление класса по идентификатору
      operationId: removeSchoolClass
      description: Удаление класса по идентификатору
      tags:
        - school-class
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '422':
          description: Unprocessable Entity (WebDAV)
  #  Предметы
  /subject:
    parameters: []
    get:
      summary: Получение списка предметов по параметрам
      operationId: findSubjects
      description: Получение списка предметов по параметрам
      tags:
        - subject
      parameters:
        - $ref: '#/components/parameters/search'
      responses:
        '200':
          description: OK
          headers: { }
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubjectDTO'
              examples:
                example-1:
                  value:
                    - id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
                      systemName: string
                      name: string
                      description: string
    post:
      summary: Создание предмета
      operationId: addSubject
      description: Создание предмета
      tags:
        - subject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubjectDTO'
            examples:
              example-1:
                value:
                  id: 1
                  systemName: string
                  name: string
                  description: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubjectDTO'
              examples:
                example-1:
                  value:
                    id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
                    systemName: string
                    name: string
                    description: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '422':
          description: Unprocessable Entity (WebDAV)
  '/subject/{subjectId}':
    parameters:
      - $ref: '#/components/parameters/subjectId'
    get:
      summary: Получение предмета по идентификатору
      operationId: findSubjectById
      description: Получение предмета по идентификатору
      tags:
        - subject
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubjectDTO'
              examples:
                example-1:
                  value:
                    id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
                    systemName: string
                    name: string
                    description: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '422':
          description: Unprocessable Entity (WebDAV)
    put:
      summary: Метод изменяет предмет
      operationId: modifySubject
      description: Метод изменяет предмет
      tags:
        - subject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubjectDTO'
            examples:
              example-1:
                value:
                  id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
                  systemName: string
                  name: string
                  description: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubjectDTO'
              examples:
                example-1:
                  value:
                    id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
                    systemName: string
                    name: string
                    description: string
        '400':
          description: Bad Request
        '422':
          description: Unprocessable Entity (WebDAV)
    delete:
      summary: Удаление предмета по идентификатору
      operationId: removeSubject
      description: Удаление предмета по идентификатору
      tags:
        - subject
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '422':
          description: Unprocessable Entity (WebDAV)
  #  Школьные тесты
  /school-test:
    parameters: []
    get:
      summary: Получение списка школьных тестов по параметрам
      operationId: findSchoolTests
      description: Получение списка школьных тестов по параметрам
      tags:
        - school-test
      parameters:
        - $ref: '#/components/parameters/searchSchoolClassId'
        - $ref: '#/components/parameters/searchSubjectId'
      responses:
        '200':
          description: OK
          headers: { }
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SchoolTestResDTO'
              examples:
                example-1:
                  value:
                    - id: 7dafaf2b-3fd8-45d4-b658-84493ed622aa
                      schoolClass:
                        id: b06e7544-a62a-42a3-b937-73508dae48c7
                        systemName: string
                        name: string
                        description: string
                      subject:
                        id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
                        systemName: string
                        name: string
                        description: string
                      displayName: string
    post:
      summary: Создание школьного теста
      operationId: addSchoolTest
      description: Создание школьного теста
      tags:
        - school-test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchoolTestReqDTO'
            examples:
              example-1:
                value:
                  id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
                  schoolClassId: string
                  subjectId: string
                  displayName: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchoolTestResDTO'
              examples:
                example-1:
                  value:
                    - id: 7dafaf2b-3fd8-45d4-b658-84493ed622aa
                      schoolClass:
                        id: b06e7544-a62a-42a3-b937-73508dae48c7
                        systemName: string
                        name: string
                        description: string
                      subject:
                        id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
                        systemName: string
                        name: string
                        description: string
                      displayName: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '422':
          description: Unprocessable Entity (WebDAV)
  '/school-test/{schoolTestId}':
    parameters:
      - $ref: '#/components/parameters/schoolTestId'
    get:
      summary: Получение школьного теста по идентификатору
      operationId: findSchoolTestById
      description: Получение школьного теста по идентификатору
      tags:
        - school-test
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchoolTestResDTO'
              examples:
                example-1:
                  value:
                    - id: 7dafaf2b-3fd8-45d4-b658-84493ed622aa
                      schoolClass:
                        id: b06e7544-a62a-42a3-b937-73508dae48c7
                        systemName: string
                        name: string
                        description: string
                      subject:
                        id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
                        systemName: string
                        name: string
                        description: string
                      displayName: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '422':
          description: Unprocessable Entity (WebDAV)
    put:
      summary: Метод изменяет школьный тест
      operationId: modifySchoolTest
      description: Метод изменяет школьный тест
      tags:
        - school-test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchoolTestReqDTO'
            examples:
              example-1:
                value:
                  id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
                  schoolClassId: string
                  subjectId: string
                  displayName: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchoolTestResDTO'
              examples:
                example-1:
                  value:
                    - id: 7dafaf2b-3fd8-45d4-b658-84493ed622aa
                      schoolClass:
                        id: b06e7544-a62a-42a3-b937-73508dae48c7
                        systemName: string
                        name: string
                        description: string
                      subject:
                        id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
                        systemName: string
                        name: string
                        description: string
                      displayName: string
        '400':
          description: Bad Request
        '422':
          description: Unprocessable Entity (WebDAV)
    delete:
      summary: Удаление школьного теста по идентификатору
      operationId: removeSchoolTest
      description: Удаление школьного теста по идентификатору
      tags:
        - school-test
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '422':
          description: Unprocessable Entity (WebDAV)

components:
  schemas:
    ErrorDTO:
      title: ErrorDTO
      type: object
      additionalProperties: false
      description: Объект ошибки
      x-examples:
        example-1:
          code: 1
          message: string
      properties:
        code:
          type: integer
          format: int64
          description: Код ошибки
          minimum: 0
          maximum: 2147483647
        message:
          type: string
          description: Текст ошибки
          maxLength: 256
    SchoolClassDTO:
      title: SchoolClassDTO
      type: object
      additionalProperties: false
      description: Класс
      x-examples:
        example-1:
          id: b06e7544-a62a-42a3-b937-73508dae48c7
          systemName: string
          name: string
          description: string
      properties:
        id:
          type: string
          description: Уникальный идентификатор
          format: uuid
        systemName:
          type: string
          description: Системное имя
          maxLength: 50
        name:
          type: string
          description: Имя
          maxLength: 50
        description:
          type: string
          description: Описание
          maxLength: 255
      required:
        - systemName
        - name
    SubjectDTO:
      title: SubjectDTO
      type: object
      additionalProperties: false
      description: Предмет
      x-examples:
        example-1:
          id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
          systemName: string
          name: string
          description: string
      properties:
        id:
          type: string
          description: Уникальный идентификатор
          format: uuid
        systemName:
          type: string
          description: Системное имя
          maxLength: 50
        name:
          type: string
          description: Имя
          maxLength: 50
        description:
          type: string
          description: Описание
          maxLength: 255
      required:
        - systemName
        - name
    AnswerTypeDTO:
      title: AnswerTypeDTO
      type: object
      additionalProperties: false
      description: Тип ответа
      x-examples:
        example-1:
          id: 39347391-0a0f-4834-821b-c26b7a0970c2
          systemName: string
          name: string
          description: string
      properties:
        id:
          type: string
          description: Уникальный идентификатор
          format: uuid
        systemName:
          type: string
          description: Системное имя
          maxLength: 50
        name:
          type: string
          description: Имя
          maxLength: 50
        description:
          type: string
          description: Описание
          maxLength: 255
      required:
        - systemName
        - name
    AnswerPositionDTO:
      title: AnswerPositionDTO
      type: object
      additionalProperties: false
      description: Позиция ответа
      x-examples:
        example-1:
          id: de564cf7-92b3-4078-a0b4-9e66dbe523b4
          systemName: string
          name: string
          description: string
      properties:
        id:
          type: string
          description: Уникальный идентификатор
          format: uuid
        systemName:
          type: string
          description: Системное имя
          maxLength: 50
        name:
          type: string
          description: Имя
          maxLength: 50
        description:
          type: string
          description: Описание
          maxLength: 255
      required:
        - systemName
        - name
    AnswerTypingFormatDTO:
      title: AnswerTypingFormatDTO
      type: object
      additionalProperties: false
      description: Формат ответа на задания с типом typing
      x-examples:
        example-1:
          id: f6989c2f-64b1-454d-93a7-e0ea16bd04b7
          systemName: string
          name: string
          description: string
      properties:
        id:
          type: string
          description: Уникальный идентификатор
          format: uuid
        systemName:
          type: string
          description: Системное имя
          maxLength: 50
        name:
          type: string
          description: Имя
          maxLength: 50
        description:
          type: string
          description: Описание
          maxLength: 255
      required:
        - systemName
        - name
    AnswerChooseTypeDTO:
      title: AnswerChooseTypeDTO
      type: object
      additionalProperties: false
      description: Способ выбора ответа на задания с типом choose
      x-examples:
        example-1:
          id: a719360b-e4c1-4dbb-b7ce-9a283a9a1232
          systemName: string
          name: string
          description: string
      properties:
        id:
          type: string
          description: Уникальный идентификатор
          format: uuid
        systemName:
          type: string
          description: Системное имя
          maxLength: 50
        name:
          type: string
          description: Имя
          maxLength: 50
        description:
          type: string
          description: Описание
          maxLength: 255
      required:
        - systemName
        - name
    AnswerChooseColorDTO:
      title: AnswerChooseColorDTO
      type: object
      additionalProperties: false
      description: Цвет выбора ответа на задания с типом choose
      x-examples:
        example-1:
          id: aa80130b-f296-4131-89b1-6ef3008b081d
          systemName: string
          name: string
          description: string
      properties:
        id:
          type: string
          description: Уникальный идентификатор
          format: uuid
        systemName:
          type: string
          description: Системное имя
          maxLength: 50
        name:
          type: string
          description: Имя
          maxLength: 50
        description:
          type: string
          description: Описание
          maxLength: 255
      required:
        - systemName
        - name
    ViewTypeDTO:
      title: ViewTypeDTO
      type: object
      additionalProperties: false
      description: Тип отображения задания
      x-examples:
        example-1:
          id: ed9b32be-1c36-4ae6-a4cc-c9494d53fca0
          systemName: string
          name: string
          description: string
      properties:
        id:
          type: string
          description: Уникальный идентификатор
          format: uuid
        systemName:
          type: string
          description: Системное имя
          maxLength: 50
        name:
          type: string
          description: Имя
          maxLength: 50
        description:
          type: string
          description: Описание
          maxLength: 255
      required:
        - systemName
        - name
    SchoolTestReqDTO:
      title: SchoolTestReqDTO
      type: object
      additionalProperties: false
      description: Входящий объект с информацией по школьному тесту
      x-examples:
        example-1:
          id: 7dafaf2b-3fd8-45d4-b658-84493ed622aa
          schoolClassId: b06e7544-a62a-42a3-b937-73508dae48c7
          subjectId: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
          displayName: string
      properties:
        id:
          type: string
          description: Уникальный идентификатор теста
          format: uuid
        schoolClassId:
          type: string
          description: Уникальный идентификатор класса
          format: uuid
        subjectId:
          type: string
          description: Уникальный идентификатор предмет
          format: uuid
        displayName:
          type: string
          description: Отображаемое имя
          maxLength: 255
      required:
        - schoolClassId
        - subjectId
    SchoolTestResDTO:
      title: SchoolTestResDTO
      type: object
      additionalProperties: false
      description: Исходящий объект с информацией по школьному тесту
      x-examples:
        example-1:
          id: 7dafaf2b-3fd8-45d4-b658-84493ed622aa
          schoolClass:
            id: b06e7544-a62a-42a3-b937-73508dae48c7
            systemName: string
            name: string
            description: string
          subject:
            id: c9e86aa4-dea3-4cec-885f-a601c9ad21dd
            systemName: string
            name: string
            description: string
          displayName: string
      properties:
        id:
          type: string
          description: Уникальный идентификатор
          format: uuid
        schoolClass:
          $ref: '#/components/schemas/SchoolClassDTO'
        subject:
          $ref: '#/components/schemas/SubjectDTO'
        displayName:
          type: string
          description: Отображаемое название
          maxLength: 255
  parameters:
    search:
      name: search
      in: query
      schema:
        type: string
        maxLength: 50
      description: Строка для поиска
    searchSchoolClassId:
      name: searchSchoolClassId
      in: query
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор класса
    searchSubjectId:
      name: searchSubjectId
      in: query
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор предмета
    searchAnswerTypeId:
      name: searchAnswerTypeId
      in: query
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор типа ответа
    searchAnswerPositionId:
      name: searchAnswerPositionId
      in: query
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор позиции ответа
    searchAnswerTypingFormatId:
      name: searchAnswerTypingFormatId
      in: query
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор формата ответа на задание с типом typing
    searchAnswerChooseTypeId:
      name: searchAnswerChooseTypeId
      in: query
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор способа выбора ответа на задание с типом choose
    searchAnswerChooseColorId:
      name: searchAnswerChooseColorId
      in: query
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор цвета выбора ответа на задание с типом choose
    searchViewTypeId:
      name: searchViewTypeId
      in: query
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор типа отображения задания
    schoolClassId:
      name: schoolClassId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор класса
    subjectId:
      name: subjectId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор предмета
    answerTypeId:
      name: answerTypeId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор типа ответа
    answerPositionId:
      name: answerPositionId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор позиции ответа
    answerTypingFormatId:
      name: answerTypingFormatId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор формата ответа на задание с типом typing
    answerChooseTypeId:
      name: answerChooseTypeId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор способа выбора ответа на задание с типом choose
    answerChooseColorId:
      name: answerChooseColorId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор цвета выбора ответа на задание с типом choose
    viewTypeId:
      name: viewTypeId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор типа отображения задания
    schoolTestId:
      name: schoolTestId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Идентификатор теста
tags:
  - name: school-classes
  - name: school-class
  - name: subjects
  - name: subject
  - name: school-tests
  - name: school-test